version: '3.7'
services:
  app_1:
    image: nginx:1.23.2-alpine
    container_name: app_1
    volumes:
      - ./config/firs.conf:/etc/nginx/conf.d/default.conf
    networks:
      - "bridge_network"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app_1.entrypoints=websecure"
      - "traefik.http.routers.app_1.rule=Host(`${DOMAIN_FIRST}`)"
      - "traefik.http.routers.app_1.service=app_1"
      - "traefik.http.services.app_1.loadbalancer.server.port=80"

  app_2:
    image: nginx:1.23.2-alpine
    container_name: app_2
    networks:
      - "bridge_network"
    volumes:
      - ./private:/var/www/var/private
      - ./config/second.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app_2.entrypoints=websecure"
      - "traefik.http.routers.app_2.rule=Host(`${DOMAIN_SECOND}`)"
      - "traefik.http.routers.app_2.service=app_2"
      - "traefik.http.services.app_2.loadbalancer.server.port=80"
  app_3:
    image: nginx:1.23.2-alpine
    container_name: app_3
    networks:
      - "bridge_network"
    volumes:
      - ./private:/var/www/var/private
      - ./config/second.conf:/etc/nginx/conf.d/default.conf


networks:
  bridge_network:
    external: true
    name: traefik